resources:
  App\Entity\User:
    shortName: 'Users'
    collectionOperations:
      post:
        path: '/register'
        openapi_context:
          summary: 'Create an account'
          description: 'Create an account'
    itemOperations:
      get: ~
    attributes:
      denormalization_context:
        groups: ['user:input']
      normalization_context:
        groups: ['user:output']

  App\Entity\ChatRooms:
    attributes:
      normalization_context:
        groups: [ 'chat_room:output' ]
      denormalization_context:
        groups: [ 'chat_room:input' ]
    collectionOperations:
      post:
        input: App\Dto\ChatRooms\Input\ChatRoomsInputDto
        output: App\Dto\ChatRooms\Output\ChatRoomsOutputDto
      get:
        filters: ['chatRooms.search_filter']
        output: App\Dto\ChatRooms\Output\ChatRoomsOutputDto
    itemOperations:
      get:
        output: App\Dto\ChatRooms\Output\ChatRoomsOutputDto
      delete: ~
      put:
        input: App\Dto\ChatRooms\Input\ChatRoomsInputDto
        output: App\Dto\ChatRooms\Output\ChatRoomsOutputDto


  App\Entity\Messages:
    collectionOperations:
      post:
        input: App\Dto\Messages\Input\MessagesInputDto
        output: App\Dto\Messages\Output\MessagesOutputDto
      get:
        filters: [ 'messages.search_filter', 'messages.range_filter' ]
        output: App\Dto\Messages\Output\MessagesOutputDto
    itemOperations:
      get:
        output: App\Dto\Messages\Output\MessagesOutputDto
      delete: ~
      put:
        input: App\Dto\Messages\Input\MessagesInputDto
        output: App\Dto\Messages\Output\MessagesOutputDto
    attributes:
      normalization_context:
        groups: [ 'message:output' ]
      denormalization_context:
        groups: [ 'message:input' ]

  App\Entity\CriteriaDeleteChatRooms:
    collectionOperations:
      post:
        openapi_context:
          summary: 'Delete resources based on several criteria'
          description: 'Delete resources based on several criteria'
        status: 200
        input: App\Dto\ChatRoomsCriteriaDelete\Input\ChatRoomsCriteriaDelete
        output: App\Dto\ChatRoomsCriteriaDelete\Output\ChatRoomsCriteriaDelete
      get:
        openapi_context:
          summary: "hidden"
    itemOperations: []
    attributes:
      id:
        identifier: true
      denormalization_context:
        groups: [ 'delete_chat_rooms:input' ]
      normalization_context:
        groups: [ 'delete_chat_rooms:output' ]
